### ISSUE TITLE
add homepage content

### ISSUE THREAD

**Issue by lukegonis** [bcgov/digital-gov#11]

**Comment by HeatherRemacle** [comment]
Hey, let's add this to get started:
With a digital mindset and methods we can:
- Ship solutions to citizens faster
- Find new insights into complex challenges
- Build once and reuse many times while improving 
- Deliver services that are effective and responsive

Keep up to date by joining our mailing list at CSILab@gov.bc.ca and visit soon as we continuously improve this site.

Contribute your feedback as we design this experience at our [Github repository].
